### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by sjuknelis** [ArmaanB/chess#1]
# Expected Behavior
Both the white and the black pieces can move.
# Current Behavior
Only the white pieces can move.
# Possible Solution
Make the black pieces move.
# Steps to Reproduce
1. Open the game
# Context (Environment)
About 78 degrees outside
# Detailed Description
When you play the game the black pieces don't move.
# Possible Implementation
If you implemented movement for the black pieces that would fix it I think.

**Comment by acheam0** [comment]
RESOLVED WONT_FIX
